apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./kustomizations/ingress-nginx-grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
