apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:cZ4fjnWD8zwLNDV/wpoZlRoXqr+QSgTsfKzpQqS8fAU=,iv:TK713qPM26X6oVY15s69AkiT8hg2NqYANBstJCupYQI=,tag:NEMJuiKhjApFDKCQ91pMTA==,type:str]
    admin-user: ENC[AES256_GCM,data:gIwzp8hgKMiUO3stBgCxnw==,iv:h9JfR3YImzxH1DCHqU3kiTPzGyJFiriLix2qVU9ROVU=,tag:f7ndtw3DxtERLrGnhNW9nA==,type:str]
kind: Secret
metadata:
    name: grafana-admin
sops:
    age:
        - recipient: age1afcgy452mzg0qx5dlk70qsu7cnsqng0xxxsrzq0v8reyqyqpwgpqcltksm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeStKMCtib2hxNy9kQTZr
            dUJpYk9QUmhjellJUkFneUticDErcFYwdzAwCnMybERSK1UyeEx2NHI1bDRHbzQ5
            TUhLcllENHNSTzJOZjdEeVFBU1k4VUkKLS0tIHNsZ2x1TVAvUmN6NjBDUC8zUUFR
            TWw2ZzlJSDRwRVJoSGV5bytqY3J2WmsKArDIwBqc3xD76O9fO7xcd6hw0RKv2mn2
            yaKrXyno2PPGbXTx07ydWkiC/quHzpIJ8XgmmL4kbb8m1P+sbzy0SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T01:17:20Z"
    mac: ENC[AES256_GCM,data:7fMjHTWG7Dt0vYDjZMGctnC6KXuJKHswY1sD8lBJ23Z7KdUu20/XY0Onf4KRkM6IER+Bv429D0hI1ihLqPiayB5jJF5Mi+qL28Fv2KxP5g19B2tvtNa8pjdCPC0ZiMBY5o9eaMHB1SPCgQ0snTyiIDRUCvEQhuNkf8jIKDJgrcs=,iv:T+/xUFQWxevu/CIuniGqF7p7uZaCJJHbaCmtvnyJtP0=,tag:BOMxzc/+YgB+BJUSTkoFNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
