apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:H40gaa6b/6fsTaf0XhyX3LPGAh117dpxYCEc4FVKHHs=,iv:QYSEwE7m9IANW7he0tAqRalmppDWk530utM3NjCbSA4=,tag:eWdGcOXuIfx5uQ8Kf16pug==,type:str]
    admin-user: ENC[AES256_GCM,data:gLzPhy5RBzlxpwpTh9a8pQ==,iv:2akb+7GhdBSt/OedkLTiir+i0aeENzFj2bOUQP1fmqI=,tag:eFWrKtioDMxSna8wr/PAvA==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age1afcgy452mzg0qx5dlk70qsu7cnsqng0xxxsrzq0v8reyqyqpwgpqcltksm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zld4OXdJNHloOXRVKzFB
            Z2RPWG84UXBDaWZwRHBGcjF0YXc0RHBiRXdjCmh3UmJLZThKMGl3dkhvc1pFdnM3
            VzJSM0Rua1BMMHNMWGNINGtzYXFoY1kKLS0tICt5SDBDV0hnV1Azb2ZkcmN6UTZV
            WXA3YmNlQk1kYmI3WVNyMVk4YlZpcTQKfgGTvi0EOKPoI4ZFO8WJEyM0rrwhXcIH
            Z72OZBJ/Op2ks8bNAM/Y1FncBMVoI9AnzekC2SZokOi7kUL41SukQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T01:58:01Z"
    mac: ENC[AES256_GCM,data:JCpgmO8FhT84YieGzR4N7fhgWwJC8yKrz4sEJ/JcMDVjdHY02/LGRaQno2u73F2PfQvtrTFJZSH+xDsZLTb4rsAncVFPy9xgNP/s7xhPW4yxx+9LCEztu6sufwuo2gGQu4NKczmXlZcsAgkS5Zlem23QnZKHmOctz4k/W0NUD0Q=,iv:DV3O1gngJZyPuCXwQnf5UWZxavBUUbrpcdopFR4dHxk=,tag:m4kkQKpCT/pTTOefXC9VOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
