apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: "Always"
        runAsNonRoot: true
        supplementalGroups: [33]
      
        volumeMounts:
        - name: linkding-data
          mountPath: /etc/linkding/data

      initContainers:
        - name: volume-permissions
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for fsGroup to apply..." && sleep 5 &&
          chown -R 33:33 /data &&
          chmod 775 /data &&
          chmod 664 /data/db.sqlite3 || true &&
          ls -la /data/
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: linkding-data
          mountPath: /data

        
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.45.0
          ports:
            - containerPort: 9090
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          env:
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: "http://192.168.2.*,http://k8sld.garberogl.io"

      envFrom:
        #- configMapRef:
        #  name: linkding-configmap
        - secretRef:
          name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /etc/linkding/data
              name: linkding-data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
