apiVersion: v1
kind: Service
metadata:
  name: linkding-lb
  namespace: linkding
spec:
  selector:
    app: linkding
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.2.240

